### ISSUE TITLE
How do you use this on the client?

### ISSUE THREAD

**Issue by hi-brylle** [carlosV2/adapter-node-ws#3]
That's it. Thank you for the plugin btw :)

**Comment by carlosV2** [comment]
Hi @hi-brylle!

I use the [JS websocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). It is really simple. For example:
```ts
const ws = new WebSocket('wss://<your domain>');
ws.addEventListener('message', (event: MessageEvent<string>) => {
  console.log('The event', event);
  console.log('The data', event.data);
});
```

In particular, it works great with svelte layouts. For example, in my current setup, I have this piece of code in a `+layout.svelte` file and I share it through a context. On any page I need to use it (usually to send data), I pull it from the context and use it. This way I make sure the connection is kept alive. To receive data, I usually do it in the layout itself (my data structure cascades down easily).

I tried to get it working initially with Socket.IO because it provides from nice fallbacks but I found some challenges that I dimmed not worth tackling so I reverted to simpler APIs. Also, in the end, it seems that websockets are supported on the bast majority of browsers so this fallback is not that necessary.

Anyway, thanks for commenting!

**Comment by hi-brylle** [comment]
Thank you for the quick reply. Just have a few more questions:

For now, I am using localhost:5173 early in this development, does this mean I have to do (in `src/routes/+layout.svelte`)

```
<script>
    import { WebSocket } from "ws";

    const ws = new WebSocket("ws://localhost:5173")
    ws.addEventListener('message', (event) => {
        console.log('The event', event);
        console.log('The data', event.data);
    });
</script>

<slot></slot>
```

Here is my `vite.config.ts` btw. I am curious about the port number here; your docs says the port here must not be what my server port is. Is this correct?

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import WebSockets from "@carlosv2/adapter-node-ws/plugin";

export default defineConfig({
	plugins: [
		sveltekit(),
		WebSockets()
	],
	server: {
		hmr: { port: 5174 }
	}
});
```

When I run `npm run dev` this is what I get.

in console:
![image](https://user-images.githubusercontent.com/55132223/229384996-e98c4989-79d5-460c-9a03-9edd6ede9814.png)

but in my browser I get this:
![image](https://user-images.githubusercontent.com/55132223/229385070-83b5248f-89d8-460a-a571-b7af23f2d5ef.png)

What am I missing here? 

For completeness, here is my `hooks.server.ts`:
```
import type { WebSocketServer } from "ws"

export const handleWs = (wss: WebSocketServer) => {
    wss.on("connection", (ws) => {
        ws.send("Hello World!");
    });
};
```

and my `svelte.config.js`:
```
import adapter from "@carlosv2/adapter-node-ws/adapter";
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	}
};

export default config;
```

Thank you.

**Comment by carlosV2** [comment]
Ok, let me see if I can help you with this.

> For now, I am using localhost:5173 early in this development, does this mean I have to do (in `src/routes/+layout.svelte`)
> 
> ```
> <script>
>     import { WebSocket } from "ws";
> 
>     const ws = new WebSocket("ws://localhost:5173")
>     ws.addEventListener('message', (event) => {
>         console.log('The event', event);
>         console.log('The data', event.data);
>     });
> </script>
> 
> <slot></slot>
> ```

Sorry, I think I wasn't clear enough. Because you want to use a native API, you don't need to import anything in the client side since `WebSocket` is already a global object. You only need to import it in the server side (i.e. your hooks) because NodeJS does not have a native websockets library.

In addition to this, unless you have restricted SvelteKit to only run in the client (I can tell you haven't from your screenshots), you will need to be 100% certain that you initialise the websocket in the browser only (as opposed to running during SSR). For example, I'm using [`onMount`](https://svelte.dev/docs#run-time-svelte-onmount) to ensure this condition.

Finally, a minor comment: in my case, I'm using the websocket in the layout because I need to navigate back and forth several pages and I want to keep the connection alive. If all your processing happens within a single page alone, you can very well initialise it in that page.

> Here is my `vite.config.ts` btw. I am curious about the port number here; your docs says the port here must not be what my server port is. Is this correct?
> 
> ```
> import { sveltekit } from '@sveltejs/kit/vite';
> import { defineConfig } from 'vite';
> import WebSockets from "@carlosv2/adapter-node-ws/plugin";
> 
> export default defineConfig({
> 	plugins: [
> 		sveltekit(),
> 		WebSockets()
> 	],
> 	server: {
> 		hmr: { port: 5174 }
> 	}
> });
> ```

Yes, this is correct. The reason is that Vite implements HMR with a websocket and no matter what I tried, I couldn't decouple both websockets so the easiest solution I found was to ask for a different HMR port. This makes HMR to still work beautifully while it frees the original port for the websocket server provided by the adapter. This, however, is only an issue during development as production does not have HMR capabilities and thus, there isn't a second websocket going on.

> When I run `npm run dev` this is what I get.
> 
> in console: ![image](https://user-images.githubusercontent.com/55132223/229384996-e98c4989-79d5-460c-9a03-9edd6ede9814.png)
> 
> but in my browser I get this: ![image](https://user-images.githubusercontent.com/55132223/229385070-83b5248f-89d8-460a-a571-b7af23f2d5ef.png)
> 
> What am I missing here?

This is due to a mixture of problems commented in the first point. Since you are importing the websocket from `ws`, it allows the server to connect to a websocket (well, the goods news is that it seems like your websocket server is working!). In addition, because you are not guaranteeing the execution on the client only, it is actually being called during SSR. This is why it works while the page is being rendered in the server but it fails on the client. Basically, follow the initial point to fix it.

> For completeness, here is my `hooks.server.ts`:
> 
> ```
> import type { WebSocketServer } from "ws"
> 
> export const handleWs = (wss: WebSocketServer) => {
>     wss.on("connection", (ws) => {
>         ws.send("Hello World!");
>     });
> };
> ```

Yup, this looks good to me (in fact, thanks to your server console, I think I can tell it works fine).

> and my `svelte.config.js`:
> 
> ```
> import adapter from "@carlosv2/adapter-node-ws/adapter";
> import { vitePreprocess } from '@sveltejs/kit/vite';
> 
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
> 	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
> 	// for more information about preprocessors
> 	preprocess: vitePreprocess(),
> 
> 	kit: {
> 		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
> 		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
> 		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
> 		adapter: adapter()
> 	}
> };
> 
> export default config;
> ```

Also looking good.

Just try to fix the initial point and I have no doubt your will get it working shortly.

Good luck!

**Comment by hi-brylle** [comment]
Oh `onMount` was the missing sauce. It's working now, big thanks!
